### ISSUE TITLE
Bug no Aul

### ISSUE THREAD

**Issue by jhonatheberson** [jhonatheberson/programmable-processor#4]
professor estou com problema no inverter, pois a saída não esta saindo, e no And, acho que não esta correto. por favor verifique está no branch Bug
@kenreurisondca

**Comment by kenreurisondca** [comment]
@jhonatheberson, Já conseguiu resolver?

**Comment by jhonatheberson** [comment]
não, pode me ajudar por favor

**Comment by jhonatheberson** [comment]
estou na UFRN, caso se poder me atender?

**Comment by kenreurisondca** [comment]
Olá Jhonat,

até estava na UFRN, mas muito ocupado. Acabei que não vi sua mensagem.
Apareça amanhã para tirar dúvidas.

Em seg, 17 de jun de 2019 às 16:04, Jhonat Heberson Avelino de Souza <
notifications@github.com> escreveu:

**Comment by jhonatheberson** [comment]
resolvido. obrigado, problema no multiplexador
